name: Rob Dickenson
favicon: null
layout_spectrum: 0
typography_spectrum: 0.32086
title: Rob Dickenson  •  Musician  •  Writer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1b346c'
    - '#01abe9'
    - '#f54b1a'
    - '#bf1106'
  brandStrength: 0.8125
  lightness: 0.375
  saturation: 0.4375
  rhythmicContrast: 1
purpose: []
