name: Rob Dickenson
favicon: null
layout_spectrum: 0.592227665707469
typography_spectrum: 0.07205265923403203
title: Rob Dickenson  •  Musician  •  Writer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#555555'
    - '#fefefe'
    - '#141414'
    - '#9e9e9e'
    - '#bebebe'
  brandStrength: 0.26053758966736495
  lightness: 0.3498430910985917
  saturation: 0.6554532938171178
  rhythmicContrast: 0.7025929701048881
purpose: []
